services:
    
  web: 
    build: ./docker-config/php
    volumes:
      - ./webApp:/var/www
      - ./docker-config/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "5173:5173"
    depends_on:
      - postgres
    command: >
      sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
             chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
             php-fpm"

    # restart: always

  nginx:
    # image: nginx
    build: ./docker-config/nginx
    ports:
      - "8080:80"
    volumes:
      - ./webApp:/var/www
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    # restart: always

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: stupro
      POSTGRES_PASSWORD: stupro
      PGPASSWORD: stupro
      POSTGRES_DB: main
      TZ: "Asia/Tokyo"
    ports:
      - 54320:5432
    volumes:
      - ./docker-config/postgres/data:/var/lib/postgresql/data
      - ./docker-config/postgres/logs:/var/log
    # restart: always